//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimeraAplicacionWebConEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viaje()
        {
            this.Asiento = new HashSet<Asiento>();
            this.DETALLEVENTA = new HashSet<DETALLEVENTA>();
        }
    
        public int IIDVIAJE { get; set; }
        public Nullable<int> IIDLUGARORIGEN { get; set; }
        public Nullable<int> IIDLUGARDESTINO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<System.DateTime> FECHAVIAJE { get; set; }
        public Nullable<int> IIDBUS { get; set; }
        public Nullable<int> NUMEROASIENTOSDISPONIBLES { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public byte[] FOTO { get; set; }
        public string nombrefoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiento> Asiento { get; set; }
        public virtual Bus Bus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEVENTA> DETALLEVENTA { get; set; }
        public virtual Lugar Lugar { get; set; }
        public virtual Lugar Lugar1 { get; set; }
    }
}
